title: Liang Peng's Github.io
page-top-title: Liang Peng's Homepage
top-section-bg-text: 'Thoroughly conscious ignorance is the prelude to every real advance in science. —— James Clerk Maxwell'
home-subtitle: Liang Peng
copyright-text: 'Template From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
